CREATE TABLE MYMONEYCATEGORY
  (
    CATEGORYTYPEID   NUMBER NOT NULL ,
    CATEGORYTYPENAME VARCHAR2 (50) ,
    CREATEDBY        VARCHAR2 (50) ,
    MODIFIEDBY       VARCHAR2 (50) ,
    CREATEDDATE      DATE ,
    MODIFIEDDATE     DATE
  ) ;
