CREATE TABLE MYMONEYACCOUNTTYPE
  (
    BANKACCOUNTTYPEID NUMBER NOT NULL ,
    ACCOUNTTYPENAME   VARCHAR2 (50) ,
    CREATEDBY         VARCHAR2 (50) ,
    MODIFIEDBY        VARCHAR2 (50) ,
    CREATEDDATE       DATE ,
    MODIFIEDDATE      DATE
  ) ;
