--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE MYMONEYTRANSACTION ADD CONSTRAINT MYMONEYTRANSACTION_MYMONEYCATEGORY_FK FOREIGN KEY ( MYMONEYCATEGORY_CATEGORYTYPEID ) REFERENCES MYMONEYCATEGORY ( CATEGORYTYPEID ) ;
