--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE MYMONEYTRANSACTION ADD CONSTRAINT MYMONEYTRANSACTION_BANKACCOUNT_FK FOREIGN KEY ( BANKACCOUNT_BANKACCOUNTID ) REFERENCES BANKACCOUNT ( BANKACCOUNTID ) ;
