CREATE TABLE MYMONEYTRANSACTIONTYPE
  (
    TRANSACTIONTYPEID   NUMBER NOT NULL ,
    TRANSACTIONTYPENAME VARCHAR2 (50) ,
    CREATEDDATE         DATE ,
    MODIFIEDDATE        DATE ,
    CREATEDBY           VARCHAR2 (50) ,
    MODIFIEDBY          VARCHAR2 (50)
  ) ;
