CREATE TABLE MYMONEYUSER
  (
    FIRSTNAME    VARCHAR2 (50) ,
    LASTNAME     VARCHAR2 (50) ,
    USERNAME     VARCHAR2 (50) ,
    USERID       NUMBER NOT NULL ,
    PASSWORD     VARCHAR2 (15) ,
    EMAIL        VARCHAR2 (30) ,
    PHONENUMBER  VARCHAR2 (15) ,
    CREATEDBY    VARCHAR2 (50) ,
    MODIFIEDBY   VARCHAR2 (50) ,
    CREATEDDATE  DATE ,
    MODIFIEDDATE DATE
  ) ;
